name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'       
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}    
      - name: Install dependencies
        run: npm ci      
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
